USE [BookReviews]
GO

CREATE TABLE [dbo].[Exception] (
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Error] VARCHAR(MAX) NOT NULL,
	[StackTrace] VARCHAR(MAX) NULL,
	[DateAdded] DATETIME NOT NULL,
	[Message] VARCHAR(500) NULL,
	[Method] VARCHAR(500) NULL,
	[Arguments] VARCHAR(1000) NULL,
	[UserId] INT DEFAULT 0
	CONSTRAINT PK_Exception PRIMARY KEY ([Id])
);
GO

ALTER TABLE [dbo].[Review] ALTER COLUMN [Notes] VARCHAR(4000) NULL;
GO
